#!/bin/bash

if [ $# -ne 1 ]
then
  echo "usage: $0 settings.conf"
  exit 1
fi

userSettings=$1
source ${userSettings}

if [ $? -ne 0 ]
then
  echo "Failed to source configuration file '${userSettings}'"
  exit 1
fi

scriptDirectory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Send the jobs with qsub
for run in ${runs}
do
  for energy in ${energies}
  do
    for skip in 0 1 2 3 4 5 6 7 8 9
    do
      qsub -N simuds${energy}_${run}_${skip} ${scriptDirectory}/run-ddsim-uds ${userSettings} ${energy} ${run} ${skip}
    done
  done
done
