######################################################
# HTCondor Submit Description File. COMMON TEMPLATE
#     htc_job_singleMuon.sub
# Next to submit it to BIRD:
#     condor_submit htc_job_singleMuon.sub
######################################################

# Default Universe for normal jobs
Universe = vanilla
+MyProject = "af-ilc"
Requirements = OpSysAndVer=="SL6"

InitialDir = $ENV(PWD)

# Here is for your Executable file
Executable = run_singleMuon.sh
transfer_executable = True
Should_Transfer_Files = IF_NEEDED

# Infos from your job: Name them in your way
Output = $(Cluster).$(Process).out
Error = $(Cluster).$(Process).err
Log = $(Cluster).$(Process).log

# Mailing requests: Update as you need
Notification = Always

# BIRD resources requests: Update as you need
+RequestRuntime = 3600 * 3
RequestMemory = 1024 * 2
RequestDisk = 2048 * 3
RequestCpus = 10

Queue 1
